# Generated by Django 3.1.5 on 2021-01-08 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='licence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_licence', to='backend_test_app.licence'),
        ),
    ]
