# Generated by Django 3.1.5 on 2021-01-08 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_test_app', '0002_auto_20210108_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licence_company', to='backend_test_app.company'),
        ),
    ]
